M48
; DRILL file {KiCad (6.0.6)} date Sat Oct 21 22:29:03 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-21T22:29:03+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X108.585Y-69.215
X108.585Y-103.505
X163.195Y-69.215
X163.195Y-103.505
T0
M30
